"""Self-contained HTML page generation with embedded Mermaid.js diagrams."""

from __future__ import annotations

from pathlib import Path
from string import Template

_VENDOR_DIR = Path(__file__).parent / "vendor"

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title</title>
    <style>
        :root {
            --bg: #1e1e2e;
            --bg-header: #181825;
            --border: #313244;
            --text: #cdd6f4;
            --text-muted: #6c7086;
            --accent: #cba6f7;
        }
        [data-theme="light"] {
            --bg: #eff1f5;
            --bg-header: #e6e9ef;
            --border: #bcc0cc;
            --text: #4c4f69;
            --text-muted: #8c8fa1;
            --accent: #8839ef;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            background: var(--bg);
            color: var(--text);
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                         'Helvetica Neue', Arial, sans-serif;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            transition: background 0.2s, color 0.2s;
        }
        header {
            padding: 0.75rem 1.5rem;
            background: var(--bg-header);
            border-bottom: 1px solid var(--border);
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        header h1 {
            font-size: 1rem;
            font-weight: 500;
            color: var(--accent);
        }
        .theme-toggle {
            background: none;
            border: 1px solid var(--border);
            color: var(--text);
            padding: 0.3rem 0.6rem;
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.8rem;
        }
        .theme-toggle:hover {
            border-color: var(--accent);
        }
        .diagram-container {
            flex: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
            overflow: auto;
        }
        .mermaid { max-width: 100%; }
        footer {
            padding: 0.4rem 1.5rem;
            background: var(--bg-header);
            border-top: 1px solid var(--border);
            font-size: 0.7rem;
            color: var(--text-muted);
            text-align: right;
        }
    </style>
</head>
<body>
    <header>
        <h1>$title</h1>
        <button class="theme-toggle" id="themeToggle">Light</button>
    </header>
    <div class="diagram-container">
        <pre class="mermaid">
$mermaid_code
        </pre>
    </div>
    <footer>Generated by codelibrarian</footer>
    <script>
$mermaid_js
    </script>
    <script>
        const DARK_THEME = {
            theme: 'dark',
            themeVariables: {
                darkMode: true,
                background: '#1e1e2e',
                primaryColor: '#cba6f7',
                primaryTextColor: '#cdd6f4',
                primaryBorderColor: '#89b4fa',
                lineColor: '#a6adc8',
                secondaryColor: '#313244',
                tertiaryColor: '#45475a'
            }
        };
        const LIGHT_THEME = {
            theme: 'default',
            themeVariables: {
                darkMode: false,
                background: '#eff1f5',
                primaryColor: '#cba6f7',
                primaryTextColor: '#4c4f69',
                primaryBorderColor: '#7287fd',
                lineColor: '#8c8fa1',
                secondaryColor: '#e6e9ef',
                tertiaryColor: '#bcc0cc'
            }
        };

        function getPreferredTheme() {
            var saved = localStorage.getItem('codelibrarian-theme');
            return saved || 'dark';
        }

        function applyTheme(theme) {
            document.documentElement.setAttribute('data-theme', theme);
            document.getElementById('themeToggle').textContent =
                theme === 'dark' ? 'Light' : 'Dark';
            localStorage.setItem('codelibrarian-theme', theme);
        }

        async function renderMermaid(theme) {
            var config = theme === 'dark' ? DARK_THEME : LIGHT_THEME;
            config.startOnLoad = false;
            mermaid.initialize(config);
            var container = document.querySelector('.diagram-container');
            var pre = container.querySelector('pre.mermaid');
            var code = pre.getAttribute('data-original') || pre.textContent;
            pre.setAttribute('data-original', code);
            pre.removeAttribute('data-processed');
            pre.innerHTML = code;
            await mermaid.run({nodes: [pre]});
        }

        // Initial render
        var initialTheme = getPreferredTheme();
        applyTheme(initialTheme);
        document.addEventListener('DOMContentLoaded', function() {
            renderMermaid(initialTheme);
        });

        document.getElementById('themeToggle').addEventListener('click', function() {
            var current = document.documentElement.getAttribute('data-theme') || 'dark';
            var next = current === 'dark' ? 'light' : 'dark';
            applyTheme(next);
            renderMermaid(next);
        });
    </script>
</body>
</html>
""")


def _load_mermaid_js() -> str:
    """Read the vendored mermaid.min.js file."""
    js_path = _VENDOR_DIR / "mermaid.min.js"
    if not js_path.exists():
        raise FileNotFoundError(
            f"Vendored mermaid.min.js not found at {js_path}. "
            "The codelibrarian package may be installed incorrectly."
        )
    return js_path.read_text(encoding="utf-8")


def render_html(mermaid_code: str, title: str = "Diagram") -> str:
    """Render Mermaid diagram code into a self-contained HTML page.

    Parameters
    ----------
    mermaid_code:
        Raw Mermaid diagram syntax (e.g. "classDiagram\\n  ...").
    title:
        Page title shown in the header and browser tab.

    Returns
    -------
    Complete HTML string with embedded Mermaid.js — no external dependencies.
    """
    mermaid_js = _load_mermaid_js()
    return _HTML_TEMPLATE.substitute(
        title=title,
        mermaid_code=mermaid_code,
        mermaid_js=mermaid_js,
    )
